name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fail 1
      if: ${{ always() }}
      run: | 
        echo "I failed"
        exit 1

    - name: Fail 2
      if: ${{ always() }}
      run: | 
        echo "I failed"
        exit 1   

    - name: If
      if: ${{ failure() }}
      run: | 
        echo "Someone failed"

  build-2:

    runs-on: ubuntu-latest

    steps:
    - name: Fail 1
      continue-on-error: true
      run: | 
        echo "I failed"
        exit 1

    - name: Fail 2
      continue-on-error: true
      run: | 
        echo "I failed"
        exit 1   

    - name: If
      if: ${{ failure() }}
      run: | 
        echo "Someone failed"
