name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Success
      id: success-1
      run: echo "I AM GROOT"

    - name: Precondition 1
      if: ${{ always() && steps.success-1.outcome == 'success' }}
      run: echo "Precondition 1"

    - name: Fail 1
      id: fail-1
      if: true
      run: | 
        echo "I failed"
        exit 1

    - name: Precondition 2
      if: ${{ always() && steps.fail-1.outcome == 'failure' }}
      run: echo "Precondition 2"

    - name: Fail 2
      id: fail-2
      if: ${{ always() }}
      run: | 
        echo "I failed"
        exit 1   

    - name: If
      if: ${{ failure() }}
      run: | 
        echo "Someone failed"

    - name: Conclusion
      if: ${{ always() }}
      run: |
        echo "${{ steps.fail-1.conclusion }}"
        echo "${{ steps.fail-1.outcome }}"
        echo "${{ steps.fail-2.conclusion }}"
        echo "${{ steps.fail-2.outcome }}"

  build-2:

    runs-on: ubuntu-latest

    steps:
    - name: Fail 1
      id: fail-1
      continue-on-error: true
      run: | 
        echo "I failed"
        exit 1

    - name: Fail 2
      id: fail-2
      continue-on-error: true
      run: | 
        echo "I failed"
        exit 1   

    - name: If
      if: ${{ failure() }}
      run: | 
        echo "Someone failed"
    
    - name: Conclusion
      run: |
        echo "${{ steps.fail-1.conclusion }}"
        echo "${{ steps.fail-1.outcome }}"
        echo "${{ steps.fail-2.conclusion }}"
        echo "${{ steps.fail-2.outcome }}"
